# Generated by Django 3.2.7 on 2021-09-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField(unique=True)),
                ('vk_name_author', models.CharField(max_length=100)),
                ('vk_id_author', models.IntegerField()),
                ('text_question', models.TextField(max_length=1000)),
                ('telegram_id_who_answered', models.IntegerField(null=True)),
                ('telegram_name_author', models.CharField(max_length=100)),
                ('telegram_id', models.IntegerField(null=True, unique=True)),
                ('text_answer', models.TextField(max_length=1000)),
            ],
        ),
    ]
